[DQNConfig]
episodes = 800
max_steps = 1000
replay_size = 10000
batch_size = 64
learning_rate = 0.0005
epsilon_decay = 0.995
epsilon_start = 1.0
epsilon_end = 0.01
tau = 0.001
gamma = 0.99
seed = 42
observation_dim = 8
action_dim = 4